// Code generated by MockGen. DO NOT EDIT.
// Source: auth.go

// Package mock_usecase is a generated GoMock package.
package mock_usecase

import (
	context "context"
	apierr "holos-auth-api/internal/pkg/apierr"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockAuthUsecase is a mock of AuthUsecase interface.
type MockAuthUsecase struct {
	ctrl     *gomock.Controller
	recorder *MockAuthUsecaseMockRecorder
}

// MockAuthUsecaseMockRecorder is the mock recorder for MockAuthUsecase.
type MockAuthUsecaseMockRecorder struct {
	mock *MockAuthUsecase
}

// NewMockAuthUsecase creates a new mock instance.
func NewMockAuthUsecase(ctrl *gomock.Controller) *MockAuthUsecase {
	mock := &MockAuthUsecase{ctrl: ctrl}
	mock.recorder = &MockAuthUsecaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAuthUsecase) EXPECT() *MockAuthUsecaseMockRecorder {
	return m.recorder
}

// Signin mocks base method.
func (m *MockAuthUsecase) Signin(arg0 context.Context, arg1, arg2 string) (string, apierr.ApiError) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Signin", arg0, arg1, arg2)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(apierr.ApiError)
	return ret0, ret1
}

// Signin indicates an expected call of Signin.
func (mr *MockAuthUsecaseMockRecorder) Signin(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Signin", reflect.TypeOf((*MockAuthUsecase)(nil).Signin), arg0, arg1, arg2)
}

// Signout mocks base method.
func (m *MockAuthUsecase) Signout(arg0 context.Context, arg1 string) apierr.ApiError {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Signout", arg0, arg1)
	ret0, _ := ret[0].(apierr.ApiError)
	return ret0
}

// Signout indicates an expected call of Signout.
func (mr *MockAuthUsecaseMockRecorder) Signout(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Signout", reflect.TypeOf((*MockAuthUsecase)(nil).Signout), arg0, arg1)
}
