// Code generated by MockGen. DO NOT EDIT.
// Source: policy.go

// Package mock_repository is a generated GoMock package.
package mock_repository

import (
	context "context"
	entity "holos-auth-api/internal/app/api/domain/entity"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	uuid "github.com/google/uuid"
)

// MockPolicyRepository is a mock of PolicyRepository interface.
type MockPolicyRepository struct {
	ctrl     *gomock.Controller
	recorder *MockPolicyRepositoryMockRecorder
}

// MockPolicyRepositoryMockRecorder is the mock recorder for MockPolicyRepository.
type MockPolicyRepositoryMockRecorder struct {
	mock *MockPolicyRepository
}

// NewMockPolicyRepository creates a new mock instance.
func NewMockPolicyRepository(ctrl *gomock.Controller) *MockPolicyRepository {
	mock := &MockPolicyRepository{ctrl: ctrl}
	mock.recorder = &MockPolicyRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPolicyRepository) EXPECT() *MockPolicyRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockPolicyRepository) Create(arg0 context.Context, arg1 *entity.Policy) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockPolicyRepositoryMockRecorder) Create(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockPolicyRepository)(nil).Create), arg0, arg1)
}

// Delete mocks base method.
func (m *MockPolicyRepository) Delete(arg0 context.Context, arg1 *entity.Policy) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockPolicyRepositoryMockRecorder) Delete(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockPolicyRepository)(nil).Delete), arg0, arg1)
}

// FindByIDsAndNamePrefixAndUserIDAndNotDeleted mocks base method.
func (m *MockPolicyRepository) FindByIDsAndNamePrefixAndUserIDAndNotDeleted(arg0 context.Context, arg1 []uuid.UUID, arg2 string, arg3 uuid.UUID) ([]*entity.Policy, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByIDsAndNamePrefixAndUserIDAndNotDeleted", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].([]*entity.Policy)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByIDsAndNamePrefixAndUserIDAndNotDeleted indicates an expected call of FindByIDsAndNamePrefixAndUserIDAndNotDeleted.
func (mr *MockPolicyRepositoryMockRecorder) FindByIDsAndNamePrefixAndUserIDAndNotDeleted(arg0, arg1, arg2, arg3 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByIDsAndNamePrefixAndUserIDAndNotDeleted", reflect.TypeOf((*MockPolicyRepository)(nil).FindByIDsAndNamePrefixAndUserIDAndNotDeleted), arg0, arg1, arg2, arg3)
}

// FindByIDsAndUserIDAndNotDeleted mocks base method.
func (m *MockPolicyRepository) FindByIDsAndUserIDAndNotDeleted(arg0 context.Context, arg1 []uuid.UUID, arg2 uuid.UUID) ([]*entity.Policy, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByIDsAndUserIDAndNotDeleted", arg0, arg1, arg2)
	ret0, _ := ret[0].([]*entity.Policy)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByIDsAndUserIDAndNotDeleted indicates an expected call of FindByIDsAndUserIDAndNotDeleted.
func (mr *MockPolicyRepositoryMockRecorder) FindByIDsAndUserIDAndNotDeleted(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByIDsAndUserIDAndNotDeleted", reflect.TypeOf((*MockPolicyRepository)(nil).FindByIDsAndUserIDAndNotDeleted), arg0, arg1, arg2)
}

// FindByNamePrefixAndUserIDAndNotDeleted mocks base method.
func (m *MockPolicyRepository) FindByNamePrefixAndUserIDAndNotDeleted(arg0 context.Context, arg1 string, arg2 uuid.UUID) ([]*entity.Policy, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByNamePrefixAndUserIDAndNotDeleted", arg0, arg1, arg2)
	ret0, _ := ret[0].([]*entity.Policy)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByNamePrefixAndUserIDAndNotDeleted indicates an expected call of FindByNamePrefixAndUserIDAndNotDeleted.
func (mr *MockPolicyRepositoryMockRecorder) FindByNamePrefixAndUserIDAndNotDeleted(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByNamePrefixAndUserIDAndNotDeleted", reflect.TypeOf((*MockPolicyRepository)(nil).FindByNamePrefixAndUserIDAndNotDeleted), arg0, arg1, arg2)
}

// FindOneByIDAndUserIDAndNotDeleted mocks base method.
func (m *MockPolicyRepository) FindOneByIDAndUserIDAndNotDeleted(arg0 context.Context, arg1, arg2 uuid.UUID) (*entity.Policy, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindOneByIDAndUserIDAndNotDeleted", arg0, arg1, arg2)
	ret0, _ := ret[0].(*entity.Policy)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindOneByIDAndUserIDAndNotDeleted indicates an expected call of FindOneByIDAndUserIDAndNotDeleted.
func (mr *MockPolicyRepositoryMockRecorder) FindOneByIDAndUserIDAndNotDeleted(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindOneByIDAndUserIDAndNotDeleted", reflect.TypeOf((*MockPolicyRepository)(nil).FindOneByIDAndUserIDAndNotDeleted), arg0, arg1, arg2)
}

// Update mocks base method.
func (m *MockPolicyRepository) Update(arg0 context.Context, arg1 *entity.Policy) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockPolicyRepositoryMockRecorder) Update(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockPolicyRepository)(nil).Update), arg0, arg1)
}
