name: Deploy api to GitHub Container Registry

on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/deploy-api.yml

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      packages: write
      id-token: write

    steps:
      - uses: actions/checkout@v4.2.2

      - name: Login to GitHub Container registry
        uses: docker/login-action@v3.3.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup buildx
        uses: docker/setup-buildx-action@v3.7.1

      - name: Build and push
        uses: docker/build-push-action@v6.9.0
        with:
          context: .
          file: build/package/Dockerfile.deploy
          push: true
          platform: linux/amd64
          provenance: false
          tags: |
            ghcr.io/${{ github.repository_owner }}/holos-auth-api:latest
            ghcr.io/${{ github.repository_owner }}/holos-auth-api:1.2.1
