name: Test

on:
  push:
    branches:
      - "**"
      - "!main"

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4.2.1

      - name: Set up go
        uses: actions/setup-go@v5.0.2
        with:
          go-version-file: go.mod
          cache: true

      - name: Run lint
        uses: golangci/golangci-lint-action@v6.1.1

  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4.2.1

      - name: Set up go
        uses: actions/setup-go@v5.0.2
        with:
          go-version-file: go.mod
          cache: true

      - name: Run test
        run: go test ./...
